### ISSUE TITLE
Bug loaded image from firebase

### ISSUE THREAD

**Issue by Bunrealbo** [LongNg89/MP-blog4pp#24]
<img width="1224" alt="Screen Shot 2022-01-05 at 13 45 00" src="https://user-images.githubusercontent.com/85337069/148172464-24eb1084-f349-472e-a234-9ff2928e0d67.png">

`error` Cann't loaded image from firebase storage

https://firebase.google.com/docs/storage/android/download-files

**Comment by LongNg89** [comment]
kiểm tra lại mạng xem, bị `HttpException` kìa
